name: reviewdog

on: [ pull_request ]

jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta

      - name: Run textlint
        uses: tsuyoshicho/action-textlint@v2
        with:
          github_token: ${{ secrets.github_token }}
          textlint_flags: src
